### PR TITLE
Rename package from com.diffblue to org.diffblue

### PR DESCRIPTION
**Pull request by allredj**
Fuzztest does not work properly on projects in com.diffblue.
This is a bug in fuzztest, but the workaround here is straightforward.

### CODE REVIEW

**Comment by allredj** [comment]
@RicardoDiffBlue Please do a few checks before merging. For instance I can't generate essential tests for `CoreBanking.openNewAccout` (only boilerplate), but I don't know what the origin of the issue is. I'm trying with Cover CLI now.

**Comment by allredj** [comment]
@RicardoDiffBlue actually it was only a problem with an old version of the plugin. The latest plugin, as well as the cli work well with that change.

**Comment by JimmehAH** [comment]
We don't currently own the domain `diffblue.org` btw.
`io.diffblue` or `blue.diff` are package names based on other domains that we own.

**Comment by allredj** [comment]
Good point @JimmehAH. I've now changed to `io.diffblue`.

**Comment by cesaro** [comment]
`com.example` is another safe option. We use in fuzztest for unit tests

**Comment by allredj** [comment]
@RicardoDiffBlue I let you merge as soon as you're happy.

**Comment by rjmunro** [comment]
@cesaro `com.example` is not safe as we don't own it.

**Pull request merged**
